global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000']
  - job_name: 'v2-product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'V2 Product Service'
  - job_name: 'v2-order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'V2 Order Service'
  - job_name: 'v2-inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'V2 Inventory Service'
  - job_name: 'v2-notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'V2 Notification Service'

